function [ stim_template] = import_stim_template()
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here






% should save as a mat, check if it exists


% get text files in folder
path = uigetdir(cd,'Select the folder containing text files');
files = dir(fullfile(path, '*.txt'));
files = {files.name}';


% make empty stimulus template struct
stim_template = struct(...
    'cam_delay_wave',[],...
    'cam_start_wave',[],...
    'CS_amp_wave',[],...
    'CS_dur_wave',[],...
    'CS_start_wave',[],...
    'DAC1_amp_wave',[],...
    'DAC1_dur_wave',[],...
    'DAC1_start_wave',[],...
    'DAC2_amp_wave',[],...
    'DAC2_dur_wave',[],...
    'DAC2_start_wave',[],...
    'DAC3_amp_wave',[],...
    'DAC3_dur_wave',[],...
    'DAC3_start_wave',[],...
    'TTL0_dur_wave',[],...
    'TTL0_start_wave',[],...
    'TTL1_dur_wave',[],...
    'TTL1_start_wave',[],...
    'US_dur_wave',[],...
    'US_start_wave',[]);


for i=1:length(files)

    fn=files{i};
    F=strcat(path,'\',fn);
    R=dlmread(F,'',1);

    
    [~,name]=fileparts(fn);
    stim_template.(name)=R;

end

end

