function [ raw_fluor, roi_labels, roi_tags ] = import_sima_mat( mat_file)
% Takes .mat files generated by my python scripts and preps it for later.
%   The .mat file contains three import variables. (1) raw: the actual
%   data, (2) labels: which is the name of the rois, and (3) tags: which is
%   the morphological tags.
%   Author: Matt Jame Davis, 08/25/2015

% CHANGES
% 07.292016
%   switched r and c in : roi_tags=cell(size(labels,2),1);
%   added line to put empty strings in empty tags



load(mat_file);

% sima will make empty tag var, must create my own empty cell array for
% later analysis
if isempty(tags)
    roi_tags=cell(size(labels,2),1);
    roi_tags(:)={''};
else
    roi_tags=cellstr(tags); % char array to cell array
end

if (size(raw,1) == 1)
    raw_fluor=permute(raw,[3,2,1]);
else
    raw_fluor=permute(raw,[3,1,2]); % puts the data into: frame x trial x roi (e.g. 60 x 80 x 151)
end
    
roi_labels=labels;


end

