function [trial_type] = trial_type_struct( )
   trial_type = struct(...
    'all',[],...    
    'cr',[],...
    'no_cr',[],...
    'blank',[],...
    'cs',[],...
    'us',[],...
    'probe',[],...
    'paired',[],...
    'bad_blink',[],...
    'bad_trial',[],...
    'stim_template',[]);

end

