function [ax1,ax2]=plot2MeanInd( y1,y2,t1,t2,yl,xl,yrange)

figure;

ax1=subplot(1,2,1)
hold on;
plot(y1,'Color',[.5 .5 .5]);
plot(mean(y1,2), 'b', 'LineWidth',3)

title(t1,...
    'FontName','Arial',...
    'FontSize',24 );
% set(gca,'XTick',[1:18], 'XTickLabel',{1:3 '' 1:14},...
%     'Ylim',[0 1]);
xlabel(xl,... 
    'FontName','Arial',...
    'FontWeight','bold',...
    'FontSize',18 );
ylabel(yl,...
    'FontName','Arial',...
    'FontWeight','bold',...
    'FontSize',18 );
ylim(yrange);
set(gca,...
    'FontName','Arial',...
    'FontWeight','bold',...
    'FontSize',14 );




ax2=subplot(1,2,2)
hold on;
plot(y2,'Color',[.5 .5 .5]);
plot(mean(y2,2), 'r', 'LineWidth',3)
title(t2,...
    'FontName','Arial',...
    'FontSize',24 );
% set(gca,'XTick',[1:18], 'XTickLabel',{1:3 '' 1:14},...
%     'Ylim',[0 1]);

xlabel(xl,...
    'FontName','Arial',...
    'FontWeight','bold',...
    'FontSize',18 );
%ylabel('Running bouts (%)');
ylim(yrange);
set(gca,...
    'FontName','Arial',...
    'FontWeight','bold',...
    'FontSize',14 );


end

